version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - setup_remote_docker
      - run: bash test/nginx-with-privileged-port-test.sh
      - run: bash test/copy-files-to-container-test.sh